version: '2.1'
services:

  tikv0:
    image: pingcap/tikv:latest
    ports:
      - "20160:20160"
    volumes:
      - ./config/tikv.toml:/tikv.toml:ro
      - ./data:/data
      - ./logs:/logs
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=172.18.1.103:20160
      - --data-dir=/data/tikv0
      - --pd=172.18.254.96:23790,172.18.254.96:23791,172.18.254.96:23792
      - --config=/tikv.toml
      - --log-file=/logs/tikv0.log
    restart: on-failure

  tikv1:
    image: pingcap/tikv:latest
    ports:
      - "20161:20160"
    volumes:
      - ./config/tikv.toml:/tikv.toml:ro
      - ./data:/data
      - ./logs:/logs
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=172.18.1.103:20161
      - --data-dir=/data/tikv1
      - --pd=172.18.254.96:23790,172.18.254.96:23791,172.18.254.96:23792
      - --config=/tikv.toml
      - --log-file=/logs/tikv1.log
    restart: on-failure

  tikv2:
    image: pingcap/tikv:latest
    ports:
      - "20162:20160"
    volumes:
      - ./config/tikv.toml:/tikv.toml:ro
      - ./data:/data
      - ./logs:/logs
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=172.18.1.103:20162
      - --data-dir=/data/tikv2
      - --pd=172.18.254.96:23790,172.18.254.96:23791,172.18.254.96:23792
      - --config=/tikv.toml
      - --log-file=/logs/tikv2.log
    restart: on-failure

  tikv3:
    image: pingcap/tikv:latest
    ports:
      - "20163:20160"
    volumes:
      - ./config/tikv.toml:/tikv.toml:ro
      - ./data:/data
      - ./logs:/logs
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=172.18.1.103:20163
      - --data-dir=/data/tikv3
      - --pd=172.18.254.96:23790,172.18.254.96:23791,172.18.254.96:23792
      - --config=/tikv.toml
      - --log-file=/logs/tikv3.log
    restart: on-failure

  tikv4:
    image: pingcap/tikv:latest
    ports:
      - "20164:20160"
    volumes:
      - ./config/tikv.toml:/tikv.toml:ro
      - ./data:/data
      - ./logs:/logs
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=172.18.1.103:20164
      - --data-dir=/data/tikv4
      - --pd=172.18.254.96:23790,172.18.254.96:23791,172.18.254.96:23792
      - --config=/tikv.toml
      - --log-file=/logs/tikv4.log
    restart: on-failure

  tikv5:
    image: pingcap/tikv:latest
    ports:
      - "20165:20160"
    volumes:
      - ./config/tikv.toml:/tikv.toml:ro
      - ./data:/data
      - ./logs:/logs
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=172.18.1.103:20165
      - --data-dir=/data/tikv5
      - --pd=172.18.254.96:23790,172.18.254.96:23791,172.18.254.96:23792
      - --config=/tikv.toml
      - --log-file=/logs/tikv5.log
    restart: on-failure

  tikv6:
    image: pingcap/tikv:latest
    ports:
      - "20166:20160"
    volumes:
      - ./config/tikv.toml:/tikv.toml:ro
      - ./data:/data
      - ./logs:/logs
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=172.18.1.103:20166
      - --data-dir=/data/tikv6
      - --pd=172.18.254.96:23790,172.18.254.96:23791,172.18.254.96:23792
      - --config=/tikv.toml
      - --log-file=/logs/tikv6.log
    restart: on-failure

  tikv7:
    image: pingcap/tikv:latest
    ports:
      - "20167:20160"
    volumes:
      - ./config/tikv.toml:/tikv.toml:ro
      - ./data:/data
      - ./logs:/logs
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=172.18.1.103:20167
      - --data-dir=/data/tikv7
      - --pd=172.18.254.96:23790,172.18.254.96:23791,172.18.254.96:23792
      - --config=/tikv.toml
      - --log-file=/logs/tikv7.log
    restart: on-failure

  tikv8:
    image: pingcap/tikv:latest
    ports:
      - "20168:20160"
    volumes:
      - ./config/tikv.toml:/tikv.toml:ro
      - ./data:/data
      - ./logs:/logs
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=172.18.1.103:20168
      - --data-dir=/data/tikv8
      - --pd=172.18.254.96:23790,172.18.254.96:23791,172.18.254.96:23792
      - --config=/tikv.toml
      - --log-file=/logs/tikv8.log
    restart: on-failure

  tidb:
    image: pingcap/tidb:latest
    ports:
      - "4000:4000"
      - "10080:10080"
    volumes:
      - ./config/tidb.toml:/tidb.toml:ro
      - ./logs:/logs
    command:
      - --store=tikv
      - --path=172.18.254.96:23790,172.18.254.96:23791,172.18.254.96:23792
      - --config=/tidb.toml
      - --log-file=/logs/tidb.log
      - --advertise-address=tidb
    depends_on:
      - "tikv0"
      - "tikv1"
      - "tikv2"
      - "tikv3"
      - "tikv4"
      - "tikv5"
      - "tikv6"
      - "tikv7"
      - "tikv8"
    restart: on-failure

  tidb1:
    image: pingcap/tidb:latest
    ports:
      - "4001:4000"
      - "10081:10080"
    volumes:
      - ./config/tidb.toml:/tidb.toml:ro
      - ./logs:/logs
    command:
      - --store=tikv
      - --path=172.18.254.96:23790,172.18.254.96:23791,172.18.254.96:23792
      - --config=/tidb.toml
      - --log-file=/logs/tidb.log
      - --advertise-address=tidb
    depends_on:
      - "tikv0"
      - "tikv1"
      - "tikv2"
      - "tikv3"
      - "tikv4"
      - "tikv5"
      - "tikv6"
      - "tikv7"
      - "tikv8"
    restart: on-failure

  tidb2:
    image: pingcap/tidb:latest
    ports:
      - "4002:4000"
      - "10082:10080"
    volumes:
      - ./config/tidb.toml:/tidb.toml:ro
      - ./logs:/logs
    command:
      - --store=tikv
      - --path=172.18.254.96:23790,172.18.254.96:23791,172.18.254.96:23792
      - --config=/tidb.toml
      - --log-file=/logs/tidb.log
      - --advertise-address=tidb
    depends_on:
      - "tikv0"
      - "tikv1"
      - "tikv2"
      - "tikv3"
      - "tikv4"
      - "tikv5"
      - "tikv6"
      - "tikv7"
      - "tikv8"
    restart: on-failure

  tidb3:
    image: pingcap/tidb:latest
    ports:
      - "4003:4000"
      - "10083:10080"
    volumes:
      - ./config/tidb.toml:/tidb.toml:ro
      - ./logs:/logs
    command:
      - --store=tikv
      - --path=172.18.254.96:23790,172.18.254.96:23791,172.18.254.96:23792
      - --config=/tidb.toml
      - --log-file=/logs/tidb.log
      - --advertise-address=tidb
    depends_on:
      - "tikv0"
      - "tikv1"
      - "tikv2"
      - "tikv3"
      - "tikv4"
      - "tikv5"
      - "tikv6"
      - "tikv7"
      - "tikv8"
    restart: on-failure

